### ISSUE TITLE
Remove net/Connectivity

### ISSUE THREAD

**Issue by zship** [mutualmobile/lavaca#117]
Files which currently depend on net/Connectivity:

components/lavaca/src/mvc/Application.js
components/lavaca/src/mvc/Controller.js
components/lavaca/src/mvc/Model.js
components/lavaca/src/util/Map.js
js/app/app.js

All of the above only use it for `Connectivity.ajax()` or `Connectivity.registerOfflineAjaxHandler()`.  Users could use their own preferred AJAX library instead of `Connectivity.ajax()` and `$.ajaxError` and `navigator.online` instead of `Connectivity.registerOfflineAjaxHandler()`.

**Comment by alexwasner** [comment]
All references to connectivity are removed. I think we should still keep this in Core as it is useful, but it is no longer bound to anything.
