### ISSUE TITLE
Mapping events to collection of collections

### ISSUE THREAD

**Issue by dannichols** [mutualmobile/lavaca#14]
Scenario: You have a collection of multiple paths, each of which is a collection of multiple points, each of which is a model with X and Y attributes that indicate position. Assuming that the collection of paths is the data passed to the view, it'd be nice if there was a way to map events from the view to the individual points without having to iterate through the paths. Problem is that if you have to manually update event handlers when the view is disposed or when paths/points are added/removed.

**Comment by alexwasner** [comment]
Wow this is from 2012. Closing as @zship is doing a lot of this with Observable
