### ISSUE TITLE
Make View#mapEvent (and applyEvents) extensible

### ISSUE THREAD

**Issue by zship** [mutualmobile/lavaca#143]
The specific motivation brought up at the Lavaca meeting was Daniel wanting to
use a newer verion of Hammer.js in a project. Hammer changed their API in 2.0,
and core lavaca depends on a specific version of 1.x. Meaning mapEvent is
currently "locked in" to Hammer 1.x.

It'd be nice to split mapEvent up into smaller chunks and, for example, allow a
subclass to add Hammer support/configuration on its own.

**Comment by alexwasner** [comment]
Since we removed hammer, I'm going to close this
