### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by zship** [mutualmobile/lavaca#155]
It looks like the unit tests are no longer running. This might be a result of the switch to CommonJS modules. Current configuration is for AMD modules.

**Comment by zship** [comment]
I think I could do this, but Alex would probably be faster. What do you think @alexwasner?

**Comment by alexwasner** [comment]
I think you are pawning work off on me! If I get time this week/weekend, I can take a look into it

**Comment by alexwasner** [comment]
Probably just need to do this http://www.syntaxsuccess.com/viewarticle/writing-jasmine-unit-tests-in-es6

**Comment by daviddulak** [comment]
I have the unit tests running now on v4 branch, but a lot of them are failing because they have Jasmine 1.x syntax and need to be updated to 2.x syntax.

**Comment by zship** [comment]
170b635
