### ISSUE TITLE
Create tutorial for building a simplified to do app on ghpages site

### ISSUE THREAD

**Issue by kellyrmilligan** [mutualmobile/lavaca#48]
What I believe would help in adoption of the framework is creating a tutorial page on getlavaca.com that would walk people through creating a simple to do app. doesn't necessarily have to be to do mvc specs, but something that will use a good portion of the fucntionality needed to begin building an application.

**Comment by alexwasner** [comment]
getlavaca.com is being revamped with tutorials. Closing this as I don't think we need a ticket
